package point.of.sale.system.screens;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.BoundedRangeModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import point.of.sale.system.classes.DBConnection;
import point.of.sale.system.classes.RoundedPanel;

public class InventoryManagementPanel extends javax.swing.JPanel {

    private final Map<String, Integer> stockInProductMap = new LinkedHashMap<>();
    private final Map<String, Integer> stockOutProductMap = new LinkedHashMap<>();
    private final Map<String, Integer> categoryMap = new LinkedHashMap<>();

    private int hoveredTableRow = -1;
    private boolean suppressFilterEvents = false;

    private JPanel lowStockCard;
    private JLabel lblLowStockTitle;
    private JLabel lblLowStockCount;
    private JLabel lblLowStockMessage;

    private static final Pattern PO_PATTERN = Pattern.compile("^PO-(\\d+)$");

    public InventoryManagementPanel() {
        initComponents();

        initializeForm();
        applyColdThemeStyling();
        createLowStockCard();
        loadAllInventoryData();
        generateNextReferenceNumber();
    }

    private void initializeForm() {
        txtAutoGenerateDate.setEditable(false);
        dateAutoGenerated.setEditable(false);

        setCurrentDates();
        initializeReasonCombo();
        initializeMonitoringTable();
        initializeSearchListener();
        initializeFilterListener();
        installNumericOnlyFields();
    }

    private void applyColdThemeStyling() {
        styleTextField(txtSearch);
        styleTextField(txtAutoGenerateDate);
        styleTextField(dateAutoGenerated);
        styleTextField(txtQuantity);
        styleTextField(txtReferenceNumber);
        styleTextField(StockOutQuantity);

        styleTextArea(txtRemarks);

        styleComboBox(cmbFilterCategory);
        styleComboBox(cmbStockInProduct);
        styleComboBox(cmbStockOutProduct);
        styleComboBox(cmbReason);

        stylePanelLikeProducts(jPanel1);
        stylePanelLikeProducts(jPanel2);
        stylePanelLikeProducts(jPanel3);

        styleHeaderBar(jPanel4);
        styleHeaderBar(jPanel5);
        styleHeaderBar(jPanel8);

        styleButton(btnSaveStockIn, new Color(59, 118, 255));
        installRoundedButtonPainter(btnSaveStockIn);

        styleButton(btnSaveStockOut, new Color(59, 118, 255));
        installRoundedButtonPainter(btnSaveStockOut);

        styleButton(btnRefresh, new Color(59, 74, 92));
        installRoundedButtonPainter(btnRefresh);

        enhanceTable(table, jScrollPane3);
        
        jLabel16.setForeground(new Color(88, 105, 136));
    }

    private void stylePanelLikeProducts(JPanel panel) {
        if (panel == null) return;
        panel.setOpaque(false);
        panel.setBorder(BorderFactory.createEmptyBorder());
    }

    private void styleHeaderBar(JPanel panel) {
        if (panel == null) return;
        panel.setOpaque(false);
        panel.setBorder(BorderFactory.createEmptyBorder());
    }

    private void styleTextField(JTextField field) {
        if (field == null) return;

        field.setFont(new Font("Tahoma", Font.PLAIN, 13));
        field.setBackground(Color.WHITE);
        field.setForeground(new Color(35, 48, 72));
        field.setCaretColor(new Color(59, 118, 255));
        field.setMargin(new Insets(2, 8, 2, 8));
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 214, 235), 1, true),
                new EmptyBorder(6, 8, 6, 8)
        ));
    }

    private void styleTextArea(JTextArea area) {
        if (area == null) return;

        area.setFont(new Font("Tahoma", Font.PLAIN, 13));
        area.setBackground(Color.WHITE);
        area.setForeground(new Color(35, 48, 72));
        area.setCaretColor(new Color(59, 118, 255));
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        area.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 214, 235), 1, true),
                new EmptyBorder(8, 8, 8, 8)
        ));
    }

    private void styleComboBox(JComboBox<?> combo) {
        if (combo == null) return;

        combo.setFont(new Font("Tahoma", Font.PLAIN, 13));
        combo.setBackground(Color.WHITE);
        combo.setForeground(new Color(35, 48, 72));
        combo.setFocusable(false);
        combo.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 214, 235), 1, true),
                new EmptyBorder(4, 8, 4, 8)
        ));
    }

    private void styleButton(JButton button, Color baseColor) {
        if (button == null) return;

        Color hoverColor = new Color(
                Math.min(baseColor.getRed() + 15, 255),
                Math.min(baseColor.getGreen() + 15, 255),
                Math.min(baseColor.getBlue() + 15, 255)
        );

        Color pressColor = new Color(
                Math.max(baseColor.getRed() - 15, 0),
                Math.max(baseColor.getGreen() - 15, 0),
                Math.max(baseColor.getBlue() - 15, 0)
        );

        Color disabledBg = new Color(189, 198, 214);
        Color disabledFg = new Color(114, 126, 145);

        button.setFont(new Font("Tahoma", Font.BOLD, 13));
        button.setForeground(Color.WHITE);
        button.setBackground(baseColor);
        button.setFocusPainted(false);
        button.setBorder(new EmptyBorder(6, 14, 6, 14));
        button.setContentAreaFilled(false);
        button.setOpaque(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        button.putClientProperty("btnBaseColor", baseColor);
        button.putClientProperty("btnHoverColor", hoverColor);
        button.putClientProperty("btnPressColor", pressColor);
        button.putClientProperty("btnDisabledBg", disabledBg);
        button.putClientProperty("btnDisabledFg", disabledFg);
        button.putClientProperty("btnColor", baseColor);

        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (!button.isEnabled()) return;
                button.putClientProperty("btnColor", hoverColor);
                button.repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (!button.isEnabled()) return;
                button.putClientProperty("btnColor", baseColor);
                button.repaint();
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if (!button.isEnabled()) return;
                button.putClientProperty("btnColor", pressColor);
                button.repaint();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (!button.isEnabled()) return;
                button.putClientProperty("btnColor", hoverColor);
                button.repaint();
            }
        });

        button.addPropertyChangeListener("enabled", evt -> {
            if (button.isEnabled()) {
                button.putClientProperty("btnColor", baseColor);
                button.setForeground(Color.WHITE);
                button.setCursor(new Cursor(Cursor.HAND_CURSOR));
            } else {
                button.putClientProperty("btnColor", disabledBg);
                button.setForeground(disabledFg);
                button.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
            button.repaint();
        });
    }

    private void installRoundedButtonPainter(JButton button) {
        if (button == null) return;

        button.setUI(new BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                JButton b = (JButton) c;
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                Color bg;
                Color fg;

                if (!b.isEnabled()) {
                    bg = (Color) b.getClientProperty("btnDisabledBg");
                    fg = (Color) b.getClientProperty("btnDisabledFg");
                    if (bg == null) bg = new Color(189, 198, 214);
                    if (fg == null) fg = new Color(114, 126, 145);
                } else {
                    bg = (Color) b.getClientProperty("btnColor");
                    fg = b.getForeground();
                    if (bg == null) bg = b.getBackground();
                }

                g2.setColor(bg);
                g2.fillRoundRect(0, 0, b.getWidth(), b.getHeight(), 16, 16);

                g2.setColor(new Color(255, 255, 255, 55));
                g2.drawRoundRect(0, 0, b.getWidth() - 1, b.getHeight() - 1, 16, 16);

                g2.setFont(b.getFont());
                java.awt.FontMetrics fm = g2.getFontMetrics();
                int x = (b.getWidth() - fm.stringWidth(b.getText())) / 2;
                int y = ((b.getHeight() - fm.getHeight()) / 2) + fm.getAscent();

                g2.setColor(fg);
                g2.drawString(b.getText(), x, y);
                g2.dispose();
            }
        });
    }

    private void initializeReasonCombo() {
        cmbReason.removeAllItems();
        cmbReason.addItem("Sale");
        cmbReason.addItem("Damaged");
        cmbReason.addItem("Return to Supplier");
        cmbReason.addItem("Other");
    }

    private void setCurrentDates() {
        String today = LocalDate.now().toString();
        txtAutoGenerateDate.setText(today);
        dateAutoGenerated.setText(today);
    }

    private void installNumericOnlyFields() {
        ((AbstractDocument) txtQuantity.getDocument()).setDocumentFilter(new IntegerOnlyFilter());
        ((AbstractDocument) StockOutQuantity.getDocument()).setDocumentFilter(new IntegerOnlyFilter());
    }

    private void initializeSearchListener() {
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                applyMonitoringFilters();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                applyMonitoringFilters();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                applyMonitoringFilters();
            }
        });
    }

    private void initializeFilterListener() {
        cmbFilterCategory.addActionListener(e -> {
            if (!suppressFilterEvents) {
                applyMonitoringFilters();
            }
        });
    }

    private void initializeMonitoringTable() {
        table.setDefaultEditor(Object.class, null);
        table.setRowHeight(38);

        table.getColumnModel().getColumn(4).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                    JTable tbl, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                        tbl, value, isSelected, hasFocus, row, column);

                label.setHorizontalAlignment(SwingConstants.CENTER);
                label.setBorder(new EmptyBorder(8, 10, 8, 10));

                String status = value == null ? "" : value.toString();

                if (isSelected) {
                    label.setBackground(new Color(214, 231, 250));
                    label.setForeground(new Color(20, 43, 67));
                    return label;
                }

                switch (status) {
                    case "In Stock":
                        label.setBackground(new Color(175, 215, 181));
                        label.setForeground(new Color(0, 90, 0));
                        break;
                    case "Low Stock":
                        label.setBackground(new Color(255, 235, 156));
                        label.setForeground(new Color(156, 87, 0));
                        break;
                    case "Out of Stock":
                        label.setBackground(new Color(255, 199, 206));
                        label.setForeground(new Color(156, 0, 6));
                        break;
                    default:
                        label.setBackground(Color.WHITE);
                        label.setForeground(Color.BLACK);
                        break;
                }

                return label;
            }
        });
    }

   private void enhanceTable(JTable table, JScrollPane scrollPane) {
    Font bodyFont = new Font("Tahoma", Font.PLAIN, 13);
    Font headerFont = new Font("Tahoma", Font.BOLD, 13);

    Color panelBg = new Color(241, 247, 253);
    Color cardBg = new Color(250, 253, 255);
    Color tableBg = new Color(255, 255, 255);
    Color stripeBg = new Color(246, 250, 254);
    Color hoverBg = new Color(235, 244, 255);
    Color headerBg = new Color(40, 56, 145);
    Color headerFg = Color.WHITE;
    Color textColor = new Color(32, 48, 70);
    Color mutedGrid = new Color(225, 234, 244);
    Color selectBg = new Color(214, 231, 250);
    Color selectFg = new Color(20, 43, 67);

    scrollPane.setBorder(BorderFactory.createEmptyBorder());
    scrollPane.setOpaque(false);
    scrollPane.setBackground(panelBg);
    scrollPane.getViewport().setOpaque(false);
    scrollPane.getViewport().setBackground(cardBg);
    scrollPane.setViewportBorder(null);

    table.setFont(bodyFont);
    table.setRowHeight(38);
    table.setShowGrid(true);
    table.setGridColor(mutedGrid);
    table.setIntercellSpacing(new Dimension(0, 1));
    table.setFocusable(false);
    table.setBackground(tableBg);
    table.setForeground(textColor);
    table.setSelectionBackground(selectBg);
    table.setSelectionForeground(selectFg);
    table.setBorder(BorderFactory.createEmptyBorder());
    table.setFillsViewportHeight(true);

    JTableHeader header = table.getTableHeader();
    header.setFont(headerFont);
    header.setPreferredSize(new Dimension(header.getWidth(), 46));
    header.setReorderingAllowed(false);
    header.setOpaque(false);

    header.setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            JLabel label = new JLabel(value == null ? "" : value.toString());
            label.setOpaque(true);
            label.setBackground(headerBg);
            label.setForeground(headerFg);
            label.setFont(headerFont);
            label.setHorizontalAlignment(SwingConstants.CENTER);
            label.setBorder(new EmptyBorder(10, 10, 10, 10));
            return label;
        }
    });

    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            label.setHorizontalAlignment(SwingConstants.CENTER);
            label.setBorder(new EmptyBorder(8, 12, 8, 12));
            label.setFont(bodyFont);

            if (isSelected) {
                label.setBackground(selectBg);
                label.setForeground(selectFg);
            } else if (row == hoveredTableRow) {
                label.setBackground(hoverBg);
                label.setForeground(textColor);
            } else {
                label.setBackground(row % 2 == 0 ? tableBg : stripeBg);
                label.setForeground(textColor);
            }

            return label;
        }
    };

    for (int i = 0; i < table.getColumnCount(); i++) {
        if (i != 4) {
            table.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    table.getColumnModel().getColumn(0).setPreferredWidth(220); // Product Name
    table.getColumnModel().getColumn(1).setPreferredWidth(180); // Category
    table.getColumnModel().getColumn(2).setPreferredWidth(130); // Current Stock
    table.getColumnModel().getColumn(3).setPreferredWidth(130); // Reorder Level
    table.getColumnModel().getColumn(4).setPreferredWidth(180); // Status

    scrollPane.setVerticalScrollBar(new ModernScrollBar());
    scrollPane.setHorizontalScrollBar(new ModernScrollBar());

    wrapScrollPaneInCard(scrollPane);

    table.addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseMoved(MouseEvent e) {
            int row = table.rowAtPoint(e.getPoint());
            if (row != hoveredTableRow) {
                hoveredTableRow = row;
                table.repaint();
            }
        }
    });

    table.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseExited(MouseEvent e) {
            hoveredTableRow = -1;
            table.repaint();
        }
    });
}

   private void wrapScrollPaneInCard(JScrollPane scrollPane) {
    Container parent = scrollPane.getParent();
    if (parent instanceof JViewport) {
        parent = parent.getParent();
    }

    if (parent != null) {
        parent.setLayout(new BorderLayout());
        parent.remove(scrollPane);

        JPanel roundedWrapper = new ShadowPanel();
        roundedWrapper.setLayout(new BorderLayout());
        roundedWrapper.setBorder(new EmptyBorder(14, 14, 14, 14));
        roundedWrapper.add(scrollPane, BorderLayout.CENTER);

        parent.add(roundedWrapper, BorderLayout.CENTER);
        parent.revalidate();
        parent.repaint();
    }
}
   public static class ShadowPanel extends JPanel {
    public ShadowPanel() {
        setOpaque(false);
        setBackground(new Color(250, 253, 255));
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int width = getWidth();
        int height = getHeight();

        g2.setColor(new Color(0, 0, 0, 20));
        g2.fillRoundRect(6, 6, width - 12, height - 12, 24, 24);

        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, width - 12, height - 12, 24, 24);

        g2.dispose();
        super.paintComponent(g);
    }
}

  private void createLowStockCard() {
    if (pnlAlert == null) {
        return;
    }

    pnlAlert.removeAll();
    pnlAlert.setLayout(new BorderLayout());
    pnlAlert.setOpaque(false);
    pnlAlert.setBorder(BorderFactory.createEmptyBorder());

    lowStockCard = new AlertCardPanel();
    lowStockCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    lowStockCard.setOpaque(false);

    lblLowStockTitle = new JLabel("LOW STOCK ALERT");
    lblLowStockTitle.setFont(new Font("Tahoma", Font.BOLD, 16));
    lblLowStockTitle.setForeground(new Color(26, 98, 46));

    lblLowStockCount = new JLabel("0");
    lblLowStockCount.setFont(new Font("Tahoma", Font.BOLD, 26));
    lblLowStockCount.setForeground(new Color(26, 98, 46));

    lblLowStockMessage = new JLabel("All monitored products are in good stock.");
    lblLowStockMessage.setFont(new Font("Tahoma", Font.PLAIN, 12));
    lblLowStockMessage.setForeground(new Color(55, 95, 60));

    lowStockCard.add(lblLowStockTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 14, 200, 22));
    lowStockCard.add(lblLowStockCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 42, 70, 32));
    lowStockCard.add(lblLowStockMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 82, 240, 20));

    pnlAlert.add(lowStockCard, BorderLayout.CENTER);

    pnlAlert.revalidate();
    pnlAlert.repaint();
}

    private void updateLowStockCard() {
        String sql = "SELECT COUNT(*) AS low_stock_count FROM products WHERE stock_quantity <= reorder_level";

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            int count = 0;
            if (rs.next()) {
                count = rs.getInt("low_stock_count");
            }

            lblLowStockCount.setText(String.valueOf(count));

            if (count == 0) {
                lblLowStockTitle.setForeground(new Color(26, 98, 46));
                lblLowStockCount.setForeground(new Color(26, 98, 46));
                lblLowStockMessage.setForeground(new Color(55, 95, 60));
                lblLowStockMessage.setText("All monitored products are in good stock.");
            } else {
                lblLowStockTitle.setForeground(new Color(156, 87, 0));
                lblLowStockCount.setForeground(new Color(184, 92, 0));
                lblLowStockMessage.setForeground(new Color(120, 76, 0));
                lblLowStockMessage.setText("Products are at or below reorder level.");
            }

            if (lowStockCard.getParent() != null) {
                lowStockCard.repaint();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load low stock alert: " + ex.getMessage());
        }
    }

    private void loadAllInventoryData() {
        loadProductsToCombos();
        loadCategoriesToFilter();
        applyMonitoringFilters();
        updateLowStockCard();
    }

    private void loadProductsToCombos() {
        stockInProductMap.clear();
        stockOutProductMap.clear();

        cmbStockInProduct.removeAllItems();
        cmbStockOutProduct.removeAllItems();

        String sql = "SELECT product_id, name FROM products ORDER BY name ASC";

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                int productId = rs.getInt("product_id");
                String productName = rs.getString("name");

                stockInProductMap.put(productName, productId);
                stockOutProductMap.put(productName, productId);

                cmbStockInProduct.addItem(productName);
                cmbStockOutProduct.addItem(productName);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load products: " + ex.getMessage());
        }
    }

    private void loadCategoriesToFilter() {
        categoryMap.clear();

        suppressFilterEvents = true;
        try {
            cmbFilterCategory.removeAllItems();
            cmbFilterCategory.addItem("All");

            String sql = "SELECT category_id, name FROM categories ORDER BY name ASC";

            try (Connection con = DBConnection.dbConnection();
                 PreparedStatement ps = con.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    int id = rs.getInt("category_id");
                    String name = rs.getString("name");

                    categoryMap.put(name, id);
                    cmbFilterCategory.addItem(name);
                }
            }

            if (cmbFilterCategory.getItemCount() > 0) {
                cmbFilterCategory.setSelectedIndex(0);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load categories: " + ex.getMessage());
        } finally {
            suppressFilterEvents = false;
        }
    }

    private void applyMonitoringFilters() {
        if (suppressFilterEvents) return;

        String keyword = txtSearch.getText().trim();
        String selectedCategory = cmbFilterCategory.getSelectedItem() == null
                ? "All"
                : cmbFilterCategory.getSelectedItem().toString();

        Integer categoryId = null;

        if (!"All".equalsIgnoreCase(selectedCategory)) {
            categoryId = categoryMap.get(selectedCategory);
        }

        if (keyword.isEmpty()) {
            keyword = null;
        }

        loadMonitoringTable(keyword, categoryId);
    }

    private void loadMonitoringTable(String keyword, Integer categoryId) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        StringBuilder sql = new StringBuilder();
        sql.append("SELECT p.name AS product_name, c.name AS category_name, ")
           .append("p.stock_quantity, p.reorder_level ")
           .append("FROM products p ")
           .append("LEFT JOIN categories c ON p.category_id = c.category_id ")
           .append("WHERE 1=1 ");

        boolean hasKeyword = keyword != null && !keyword.trim().isEmpty();
        boolean hasCategory = categoryId != null;

        if (hasKeyword) {
            sql.append("AND (p.name LIKE ? OR c.name LIKE ?) ");
        }

        if (hasCategory) {
            sql.append("AND p.category_id = ? ");
        }

        sql.append("ORDER BY p.name ASC");

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql.toString())) {

            int index = 1;

            if (hasKeyword) {
                String like = "%" + keyword.trim() + "%";
                ps.setString(index++, like);
                ps.setString(index++, like);
            }

            if (hasCategory) {
                ps.setInt(index++, categoryId);
            }

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    int currentStock = rs.getInt("stock_quantity");
                    int reorderLevel = rs.getInt("reorder_level");

                    model.addRow(new Object[]{
                        rs.getString("product_name"),
                        rs.getString("category_name"),
                        currentStock,
                        reorderLevel,
                        computeStockStatus(currentStock, reorderLevel)
                    });
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load inventory monitoring: " + ex.getMessage());
        }
    }

    private String computeStockStatus(int stockQuantity, int reorderLevel) {
        if (stockQuantity <= 0) {
            return "Out of Stock";
        } else if (stockQuantity <= reorderLevel) {
            return "Low Stock";
        } else {
            return "In Stock";
        }
    }

    private int getSelectedStockInProductId() {
        String productName = (String) cmbStockInProduct.getSelectedItem();
        Integer id = stockInProductMap.get(productName);
        return id == null ? -1 : id;
    }

    private int getSelectedStockOutProductId() {
        String productName = (String) cmbStockOutProduct.getSelectedItem();
        Integer id = stockOutProductMap.get(productName);
        return id == null ? -1 : id;
    }

    private boolean isValidPositiveInteger(String value) {
        try {
            return Integer.parseInt(value) > 0;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    private int getCurrentStock(int productId) throws SQLException {
        String sql = "SELECT stock_quantity FROM products WHERE product_id = ?";

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, productId);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("stock_quantity");
                }
            }
        }

        return 0;
    }

    private int getReorderLevel(int productId) throws SQLException {
        String sql = "SELECT reorder_level FROM products WHERE product_id = ?";

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, productId);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("reorder_level");
                }
            }
        }

        return 0;
    }

    private void clearStockInForm() {
        if (cmbStockInProduct.getItemCount() > 0) {
            cmbStockInProduct.setSelectedIndex(0);
        }
        txtQuantity.setText("");
        txtRemarks.setText("");
        setCurrentDates();
        generateNextReferenceNumber();
    }

    private void clearStockOutForm() {
        if (cmbStockOutProduct.getItemCount() > 0) {
            cmbStockOutProduct.setSelectedIndex(0);
        }
        StockOutQuantity.setText("");
        if (cmbReason.getItemCount() > 0) {
            cmbReason.setSelectedIndex(0);
        }
        setCurrentDates();
    }

    private void refreshInventoryModule() {
        txtSearch.setText("");
        clearStockInForm();
        clearStockOutForm();
        loadAllInventoryData();
        generateNextReferenceNumber();
    }

    private void generateNextReferenceNumber() {
        String sql =
                "SELECT reference_number " +
                "FROM inventory_transactions " +
                "WHERE reference_number IS NOT NULL " +
                "ORDER BY transaction_id DESC";

        int maxNumber = 1000;

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                String ref = rs.getString("reference_number");
                if (ref == null) continue;

                Matcher matcher = PO_PATTERN.matcher(ref.trim());
                if (matcher.matches()) {
                    int current = Integer.parseInt(matcher.group(1));
                    if (current > maxNumber) {
                        maxNumber = current;
                    }
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to generate reference number: " + ex.getMessage());
        }

        txtReferenceNumber.setText("PO-" + (maxNumber + 1));
    }

    private boolean isDuplicateStockInTransaction(int productId, int quantity, String referenceNumber, String dateText) {
        String sql =
                "SELECT COUNT(*) AS total " +
                "FROM inventory_transactions " +
                "WHERE product_id = ? " +
                "AND transaction_type = 'Stock In' " +
                "AND quantity = ? " +
                "AND reference_number = ? " +
                "AND transaction_date = ?";

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, productId);
            ps.setInt(2, quantity);
            ps.setString(3, referenceNumber);
            ps.setDate(4, Date.valueOf(LocalDate.parse(dateText)));

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("total") > 0;
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to validate duplicate Stock In: " + ex.getMessage());
        }

        return false;
    }

    private boolean isDuplicateStockOutTransaction(int productId, int quantity, String reason, String dateText) {
        String sql =
                "SELECT COUNT(*) AS total " +
                "FROM inventory_transactions " +
                "WHERE product_id = ? " +
                "AND transaction_type = 'Stock Out' " +
                "AND quantity = ? " +
                "AND reason = ? " +
                "AND transaction_date = ?";

        try (Connection con = DBConnection.dbConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, productId);
            ps.setInt(2, quantity);
            ps.setString(3, reason);
            ps.setDate(4, Date.valueOf(LocalDate.parse(dateText)));

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("total") > 0;
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to validate duplicate Stock Out: " + ex.getMessage());
        }

        return false;
    }

    private void saveStockIn() {
        int productId = getSelectedStockInProductId();
        String quantityText = txtQuantity.getText().trim();
        String referenceNumber = txtReferenceNumber.getText().trim();
        String remarks = txtRemarks.getText().trim();
        String dateText = txtAutoGenerateDate.getText().trim();

        if (productId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product.");
            return;
        }

        if (!isValidPositiveInteger(quantityText)) {
            JOptionPane.showMessageDialog(this, "Quantity must be a valid number greater than 0.");
            return;
        }

        if (referenceNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Reference number is required.");
            return;
        }

        int quantity = Integer.parseInt(quantityText);

        if (isDuplicateStockInTransaction(productId, quantity, referenceNumber, dateText)) {
            JOptionPane.showMessageDialog(this, "Duplicate Stock In transaction detected.");
            return;
        }

        String insertTransactionSql =
                "INSERT INTO inventory_transactions "
                + "(product_id, transaction_type, quantity, reference_number, transaction_date, reason, remarks) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        String updateProductSql =
                "UPDATE products SET stock_quantity = stock_quantity + ? WHERE product_id = ?";

        try (Connection con = DBConnection.dbConnection()) {
            con.setAutoCommit(false);

            try (PreparedStatement psInsert = con.prepareStatement(insertTransactionSql);
                 PreparedStatement psUpdate = con.prepareStatement(updateProductSql)) {

                psInsert.setInt(1, productId);
                psInsert.setString(2, "Stock In");
                psInsert.setInt(3, quantity);
                psInsert.setString(4, referenceNumber);
                psInsert.setDate(5, Date.valueOf(LocalDate.parse(dateText)));
                psInsert.setString(6, "Stock In");
                psInsert.setString(7, remarks.isEmpty() ? null : remarks);
                psInsert.executeUpdate();

                psUpdate.setInt(1, quantity);
                psUpdate.setInt(2, productId);
                psUpdate.executeUpdate();

                con.commit();

                JOptionPane.showMessageDialog(this, "Stock In saved successfully.");
                clearStockInForm();
                loadAllInventoryData();

            } catch (Exception ex) {
                con.rollback();
                JOptionPane.showMessageDialog(this, "Stock In failed: " + ex.getMessage());
            } finally {
                con.setAutoCommit(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }

    private void saveStockOut() {
        int productId = getSelectedStockOutProductId();
        String quantityText = StockOutQuantity.getText().trim();
        String reason = cmbReason.getSelectedItem() == null ? "" : cmbReason.getSelectedItem().toString();
        String dateText = dateAutoGenerated.getText().trim();

        if (productId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product.");
            return;
        }

        if (!isValidPositiveInteger(quantityText)) {
            JOptionPane.showMessageDialog(this, "Quantity must be a valid number greater than 0.");
            return;
        }

        int quantity = Integer.parseInt(quantityText);

        if (isDuplicateStockOutTransaction(productId, quantity, reason, dateText)) {
            JOptionPane.showMessageDialog(this, "Duplicate Stock Out transaction detected.");
            return;
        }

        try {
            int currentStock = getCurrentStock(productId);

            if (quantity > currentStock) {
                JOptionPane.showMessageDialog(this, "Insufficient stock available.");
                return;
            }

            String insertTransactionSql =
                    "INSERT INTO inventory_transactions "
                    + "(product_id, transaction_type, quantity, reference_number, transaction_date, reason, remarks) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?)";

            String updateProductSql =
                    "UPDATE products SET stock_quantity = stock_quantity - ? WHERE product_id = ?";

            try (Connection con = DBConnection.dbConnection()) {
                con.setAutoCommit(false);

                try (PreparedStatement psInsert = con.prepareStatement(insertTransactionSql);
                     PreparedStatement psUpdate = con.prepareStatement(updateProductSql)) {

                    psInsert.setInt(1, productId);
                    psInsert.setString(2, "Stock Out");
                    psInsert.setInt(3, quantity);
                    psInsert.setString(4, null);
                    psInsert.setDate(5, Date.valueOf(LocalDate.parse(dateText)));
                    psInsert.setString(6, reason);
                    psInsert.setString(7, null);
                    psInsert.executeUpdate();

                    psUpdate.setInt(1, quantity);
                    psUpdate.setInt(2, productId);
                    psUpdate.executeUpdate();

                    con.commit();

                    int newStock = currentStock - quantity;
                    int reorderLevel = getReorderLevel(productId);
                    String newStatus = computeStockStatus(newStock, reorderLevel);

                    if ("Low Stock".equals(newStatus)) {
                        JOptionPane.showMessageDialog(this, "Stock Out saved. Warning: product is now LOW STOCK.");
                    } else if ("Out of Stock".equals(newStatus)) {
                        JOptionPane.showMessageDialog(this, "Stock Out saved. Warning: product is now OUT OF STOCK.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Stock Out saved successfully.");
                    }

                    clearStockOutForm();
                    loadAllInventoryData();

                } catch (Exception ex) {
                    con.rollback();
                    JOptionPane.showMessageDialog(this, "Stock Out failed: " + ex.getMessage());
                } finally {
                    con.setAutoCommit(true);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error checking stock: " + ex.getMessage());
        }
        
    }
    private static class IntegerOnlyFilter extends DocumentFilter {
        @Override
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr)
                throws BadLocationException {
            if (string == null) return;
            if (string.matches("\\d+")) {
                super.insertString(fb, offset, string, attr);
            }
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                throws BadLocationException {
            if (text == null) return;
            if (text.isEmpty() || text.matches("\\d+")) {
                super.replace(fb, offset, length, text, attrs);
            }
        }
    }

    public static class ModernScrollBar extends JScrollBar {
        public ModernScrollBar() {
            setUI(new BasicScrollBarUI() {
                @Override
                protected void configureScrollBarColors() {
                    thumbColor = new Color(160, 185, 215);
                    trackColor = new Color(235, 242, 250);
                }

                @Override
                protected JButton createDecreaseButton(int orientation) {
                    return createZeroButton();
                }

                @Override
                protected JButton createIncreaseButton(int orientation) {
                    return createZeroButton();
                }

                private JButton createZeroButton() {
                    JButton button = new JButton();
                    button.setPreferredSize(new Dimension(0, 0));
                    button.setMinimumSize(new Dimension(0, 0));
                    button.setMaximumSize(new Dimension(0, 0));
                    return button;
                }

                @Override
                protected void paintTrack(Graphics g, JComponent c, java.awt.Rectangle trackBounds) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setColor(trackColor);
                    g2.fillRoundRect(trackBounds.x, trackBounds.y, trackBounds.width, trackBounds.height, 10, 10);
                    g2.dispose();
                }

                @Override
                protected void paintThumb(Graphics g, JComponent c, java.awt.Rectangle thumbBounds) {
                    if (thumbBounds.isEmpty() || !scrollbar.isEnabled()) return;

                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setColor(thumbColor);
                    g2.fillRoundRect(thumbBounds.x + 2, thumbBounds.y + 2,
                            thumbBounds.width - 4, thumbBounds.height - 4, 10, 10);
                    g2.dispose();
                }

                @Override
                protected Dimension getMinimumThumbSize() {
                    return new Dimension(30, 30);
                }
            });
            setPreferredSize(new Dimension(10, 10));
            setOpaque(false);
        }

        @Override
        public void setModel(BoundedRangeModel newModel) {
            super.setModel(newModel);
        }
    }

    public static class CleanTableCard extends JPanel {
        public CleanTableCard() {
            setOpaque(false);
            setBorder(BorderFactory.createEmptyBorder());
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int w = getWidth();
            int h = getHeight();

            g2.setColor(new Color(116, 165, 206, 45));
            g2.fillRoundRect(4, 5, w - 8, h - 8, 24, 24);

            g2.setColor(new Color(111, 165, 212));
            g2.fillRoundRect(0, 0, w - 8, h - 8, 24, 24);

            g2.setColor(Color.WHITE);
            g2.fillRoundRect(8, 8, w - 24, h - 24, 20, 20);

            g2.dispose();
            super.paintComponent(g);
        }
    }

    public static class AlertCardPanel extends RoundedPanel {
    public AlertCardPanel() {
        setOpaque(false);
        setBorder(BorderFactory.createEmptyBorder());
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int w = getWidth();
        int h = getHeight();

        Color top = new Color(234, 244, 225);
        Color bottom = new Color(193, 217, 191);

        g2.setColor(new Color(0, 0, 0, 18));
        g2.fillRoundRect(3, 4, w - 6, h - 6, 24, 24);

        GradientPaint gp = new GradientPaint(0, 0, top, 0, h, bottom);
        g2.setPaint(gp);
        g2.fillRoundRect(0, 0, w - 6, h - 6, 24, 24);

        g2.setColor(new Color(221, 192, 74));
        g2.setStroke(new BasicStroke(1.2f));
        g2.drawRoundRect(0, 0, w - 7, h - 7, 24, 24);

        g2.dispose();
        super.paintComponent(g);
    }
}

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int w = getWidth();
            int h = getHeight();

            Color top = new Color(234, 244, 225);
            Color bottom = new Color(193, 217, 191);

            g2.setColor(new Color(0, 0, 0, 18));
            g2.fillRoundRect(3, 4, w - 6, h - 6, 24, 24);

            GradientPaint gp = new GradientPaint(0, 0, top, 0, h, bottom);
            g2.setPaint(gp);
            g2.fillRoundRect(0, 0, w - 6, h - 6, 24, 24);

            g2.setColor(new Color(221, 192, 74));
            g2.setStroke(new BasicStroke(1.2f));
            g2.drawRoundRect(0, 0, w - 7, h - 7, 24, 24);

            g2.dispose();
            super.paintComponent(g);
        }


    /**
     *
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new point.of.sale.system.classes.GradientFont();
        jPanel2 = new RoundedPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new RoundedPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbStockInProduct = new javax.swing.JComboBox<>();
        txtAutoGenerateDate = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtReferenceNumber = new javax.swing.JTextField();
        btnSaveStockIn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        jPanel3 = new RoundedPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbStockOutProduct = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbReason = new javax.swing.JComboBox<>();
        btnSaveStockOut = new javax.swing.JButton();
        dateAutoGenerated = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        StockOutQuantity = new javax.swing.JTextField();
        jPanel4 = new RoundedPanel();
        jLabel3 = new javax.swing.JLabel("Add New User") {     @Override     protected void paintComponent(java.awt.Graphics g) {         java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();          g2.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING,                             java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);          float[] fractions = {0.5f, 1f};         java.awt.Color[] colors = {             java.awt.Color.WHITE,             java.awt.Color.BLUE         };          java.awt.LinearGradientPaint lgp = new java.awt.LinearGradientPaint(                 0, 0, getWidth(), 0,                 fractions, colors         );          g2.setPaint(lgp);          java.awt.FontMetrics fm = g2.getFontMetrics();         int x = (getWidth() - fm.stringWidth(getText())) / 2;         int y = ((getHeight() - fm.getHeight()) / 2) + fm.getAscent();          g2.drawString(getText(), x, y);          g2.dispose();     } };
        jPanel8 = new RoundedPanel();
        jLabel4 = new javax.swing.JLabel("Add New User") {     @Override     protected void paintComponent(java.awt.Graphics g) {         java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();          g2.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING,                             java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);          float[] fractions = {0.5f, 1f};         java.awt.Color[] colors = {             java.awt.Color.WHITE,             java.awt.Color.BLUE         };          java.awt.LinearGradientPaint lgp = new java.awt.LinearGradientPaint(                 0, 0, getWidth(), 0,                 fractions, colors         );          g2.setPaint(lgp);          java.awt.FontMetrics fm = g2.getFontMetrics();         int x = (getWidth() - fm.stringWidth(getText())) / 2;         int y = ((getHeight() - fm.getHeight()) / 2) + fm.getAscent();          g2.drawString(getText(), x, y);          g2.dispose();     } };
        jPanel5 = new RoundedPanel();
        jLabel17 = new javax.swing.JLabel("Add New User") {     @Override     protected void paintComponent(java.awt.Graphics g) {         java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();          g2.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING,                             java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);          float[] fractions = {0.5f, 1f};         java.awt.Color[] colors = {             java.awt.Color.WHITE,             java.awt.Color.BLUE         };          java.awt.LinearGradientPaint lgp = new java.awt.LinearGradientPaint(                 0, 0, getWidth(), 0,                 fractions, colors         );          g2.setPaint(lgp);          java.awt.FontMetrics fm = g2.getFontMetrics();         int x = (getWidth() - fm.stringWidth(getText())) / 2;         int y = ((getHeight() - fm.getHeight()) / 2) + fm.getAscent();          g2.drawString(getText(), x, y);          g2.dispose();     } };
        jSeparator3 = new javax.swing.JSeparator();
        pnlBasta = new RoundedPanel();
        cmbFilterCategory = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        pnlAlert = new javax.swing.JPanel();

        setBackground(new java.awt.Color(240, 248, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Manage stock in, stock out, and monitor inventory levels");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("INVENTORY MANAGEMENT");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, -1));

        jPanel2.setBackground(new java.awt.Color(122, 170, 206));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Category", "Current Stock", "Reorder Level", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(200);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(200);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(130);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(130);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 540));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 710, 560));

        jPanel1.setBackground(new java.awt.Color(122, 170, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Select Product:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Quantity:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Reference Number:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Remarks:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cmbStockInProduct.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbStockInProduct.addActionListener(this::cmbStockInProductActionPerformed);
        jPanel1.add(cmbStockInProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 40));

        txtAutoGenerateDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtAutoGenerateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 40));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 150, 40));

        txtReferenceNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtReferenceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 40));

        btnSaveStockIn.setBackground(new java.awt.Color(0, 98, 193));
        btnSaveStockIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveStockIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveStockIn.setText("SAVE STOCK IN");
        btnSaveStockIn.addActionListener(this::btnSaveStockInActionPerformed);
        jPanel1.add(btnSaveStockIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 160, 30));

        txtRemarks.setColumns(20);
        txtRemarks.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtRemarks.setRows(5);
        jScrollPane2.setViewportView(txtRemarks);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, 120));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, 390));

        jPanel3.setBackground(new java.awt.Color(122, 170, 206));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Select Product:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmbStockOutProduct.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel3.add(cmbStockOutProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Reason:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        cmbReason.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel3.add(cmbReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 40));

        btnSaveStockOut.setBackground(new java.awt.Color(0, 98, 193));
        btnSaveStockOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveStockOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveStockOut.setText("SAVE STOCK OUT");
        btnSaveStockOut.addActionListener(this::btnSaveStockOutActionPerformed);
        jPanel3.add(btnSaveStockOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 30));

        dateAutoGenerated.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel3.add(dateAutoGenerated, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Date:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Quantity:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        StockOutQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel3.add(StockOutQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 380, 240));

        jPanel4.setBackground(new java.awt.Color(18, 48, 174));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STOCK IN ENTRY");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 50));

        jPanel8.setBackground(new java.awt.Color(18, 48, 174));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STOCK OUT ENTRY");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 380, 50));

        jPanel5.setBackground(new java.awt.Color(18, 48, 174));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("STOCK MONITORING");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 230, 30));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 420, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 310, 10));

        pnlBasta.setBackground(new java.awt.Color(18, 48, 174));
        pnlBasta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbFilterCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbFilterCategory.addActionListener(this::cmbFilterCategoryActionPerformed);
        pnlBasta.add(cmbFilterCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 230, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Filter by Category:");
        pnlBasta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        pnlBasta.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Search:");
        pnlBasta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        btnRefresh.setBackground(new java.awt.Color(44, 62, 80));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        pnlBasta.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 90, 30));

        add(pnlBasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 710, 100));
        add(pnlAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 280, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFilterCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterCategoryActionPerformed
        applyMonitoringFilters();
    }//GEN-LAST:event_cmbFilterCategoryActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        applyMonitoringFilters();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSaveStockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStockOutActionPerformed
        saveStockOut();
    }//GEN-LAST:event_btnSaveStockOutActionPerformed

    private void btnSaveStockInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStockInActionPerformed
        saveStockIn();
    }//GEN-LAST:event_btnSaveStockInActionPerformed

    private void cmbStockInProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStockInProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStockInProductActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       
    }//GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField StockOutQuantity;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveStockIn;
    private javax.swing.JButton btnSaveStockOut;
    private javax.swing.JComboBox<String> cmbFilterCategory;
    private javax.swing.JComboBox<String> cmbReason;
    private javax.swing.JComboBox<String> cmbStockInProduct;
    private javax.swing.JComboBox<String> cmbStockOutProduct;
    private javax.swing.JTextField dateAutoGenerated;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlAlert;
    private javax.swing.JPanel pnlBasta;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAutoGenerateDate;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReferenceNumber;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
